version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: podcast_api
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=podcast
      - DB_USERNAME=root
      - DB_PASSWORD=secret
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: podcast
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
volumes:
  db_data: