openapi: 3.0.3
info:
  title: Podcast Platform API
  version: 1.0.0
  description: API for a podcast platform
servers:
  - url: http://localhost:8000/api
    description: Local server
paths:
  /podcasts:
    get:
      summary: List all podcasts
      parameters:
        - name: category_id
          in: query
          required: false
          schema:
            type: integer
        - name: sort_by
          in: query
          required: false
          schema:
            type: string
            enum: [title, created_at]
        - name: sort_direction
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
        - name: page
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A paginated list of podcasts
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Podcast'
  /podcasts/{id}:
    get:
      summary: Get a podcast by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Podcast details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Podcast'
  /categories:
    get:
      summary: List all categories
      responses:
        '200':
          description: A paginated list of categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
  /categories/{id}:
    get:
      summary: Get a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /episodes/{id}:
    get:
      summary: Get an episode by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Episode details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Episode'
components:
  schemas:
    Podcast:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        image:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        episodes:
          type: array
          items:
            $ref: '#/components/schemas/Episode'
        created_at:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        podcasts:
          type: array
          items:
            $ref: '#/components/schemas/Podcast'
    Episode:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        audio_url:
          type: string
        duration:
          type: integer
        podcast:
          $ref: '#/components/schemas/Podcast'
        created_at:
          type: string